name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCE_HOST }} >> ~/.ssh/known_hosts

      - name: Install Git on GCE VM
        run: |
          ssh ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_HOST }} << 'EOF'
            # Update package list and install Git
            sudo apt-get update
            sudo apt-get install -y git
          EOF
      
      - name: Install Git and Go on GCE VM
        run: |
          ssh ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_HOST }} << 'EOF'
            sudo apt-get update
            sudo apt-get install -y git golang-go
          EOF

      - name: Deploy to GCE
        run: |
          ssh ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_HOST }} << 'EOF'
            set -e

            # Check if moodbot directory exists, if not, clone it
            if [ ! -d "moodbot" ]; then
              git clone https://github.com/K-Road/discord-moodbot.git moodbot
            fi
            cd moodbot

            # Pull latest changes
            git pull origin main

            # Build the bot
            go build -o moodbot

            # Kill any previous instance
            pkill -f ./moodbot || true

            # Create systemd service file with real token
            sudo bash -c "cat > /etc/systemd/system/moodbot.service << EOL
[Unit]
Description=MoodBot Discord Bot
After=network.target

[Service]
ExecStart=/home/chrisgoode1982/moodbot/moodbot
WorkingDirectory=/home/chrisgoode1982/moodbot
Restart=always
Environment=DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}

[Install]
WantedBy=multi-user.target
EOL"

            # Reload systemd and restart the bot
            sudo systemctl daemon-reload
            sudo systemctl enable moodbot
            sudo systemctl restart moodbot
          EOF